---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    opscruise-chart-version: {{ .Values.global.opscruiseChartVersion }}
    app: k8sgw
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8sgw
  template:
    metadata:
      labels:
        app: k8sgw
        opscruisePerimeter: opscruise
        opscruiseGroup: gateways
        opscruiseProduct: k8sGW
        opscruiseStream: opscruise
        {{- if .Values.labels }}
        {{- range $label, $val := .Values.labels }}
        {{ $label }}: {{ $val }}
        {{- end }}
        {{- end }}
      annotations:
        checksum/env-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if .Values.annotations }}
        {{- range $annotation, $val := .Values.annotations }}
        {{ $annotation }}: {{ $val }}
        {{- end }}
      {{- end }}

    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.k8sgw_tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOGLEVEL
              value: "{{ .Values.logLevel }}"
          envFrom:
            - secretRef:
                name: {{ .Values.envFrom.secretRef }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      volumes:
      {{- toYaml .Values.volumes | nindent 8 }}

      restartPolicy: {{ .Values.restartPolicy }}

      {{- if .Values.tolerations }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 6 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
      {{- toYaml .Values.global.tolerations | nindent 6 }}
      {{- end }}

      {{- if .Values.affinity }}
      affinity:
      {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.global.affinity }}
      affinity:
      {{- toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      {{- if .Values.global.hostAliases }}
      hostAliases:
        {{- toYaml .Values.global.hostAliases | nindent 6 }}
      {{- end }}