# Default values for kafka-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

podLabels: {}

image:
  repository: danielqsj/kafka-exporter
  tag: v1.6.0
  pullPolicy: IfNotPresent

args:
  - --kafka.server=<KAFKA_SERVICE>.<NAMESPACE>.svc.cluster.local:<KAFKA_SERVICE_PORT>
  - --zookeeper.server=<ZOOKEEPER_SERVICE>.<NAMESPACE>.svc.cluster.local:<ZOOKEEPER_SERVICE_PORT>

containerport: 9308

service:
  type: ClusterIP
  port: 9308
  labels: {}
