{{ if eq .Values.endpoint_type "common_dns" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdbv2-exporter-svc
  namespace: {{ .Release.Namespace }}
  labels:
    opscruisePerimeter: opscruise
{{- if .Values.serviceLabels }}
{{- toYaml .Values.serviceLabels | trim | nindent 4 }}
{{- end }}
  {{- if .Values.annotations }}
  annotations:
    opscruise.prometheus/path: {{ .Values.prometheus_scrape_config.path }}
    opscruise.prometheus/port: {{ tpl .Values.prometheus_scrape_config.port . }}
    opscruise.prometheus/scheme: {{ .Values.prometheus_scrape_config.scheme }}
    opscruise.prometheus/scrape: "{{ .Values.prometheus_scrape_config.scrape }}"
    {{- range $annotation, $val := .Values.annotations }}
    {{ $annotation }}: {{ $val }}
    {{- end }}
  {{- end }}
spec:
  type: ExternalName
  externalName: {{ .Values.common_dns_name }}
  ports:
    - port: {{ .Values.common_dns_port }}
{{ else if eq .Values.endpoint_type "external_ip" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-influxdbv2-exporter-vm-svc
  namespace: {{ .Release.Namespace }}
  labels:
    opscruisePerimeter: opscruise
{{- if .Values.serviceLabels }}
{{- toYaml .Values.serviceLabels | trim | nindent 4 }}
{{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $annotation, $val := .Values.annotations }}
    {{ $annotation }}: {{ $val }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.external_ip_port }}
      targetPort: {{ .Values.external_ip_port }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-influxdbv2-exporter-vm-svc
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.external_ip_address }}
    ports:
      - port: {{ .Values.external_ip_port }}
{{ end }}