apiVersion: v1
kind: Secret
metadata:
  name: oc-aws-credential
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID:  {{ .Values.global.awsCredentials.aws_access_key_id | toString | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.awsCredentials.aws_secret_access_key | toString | b64enc | quote }}
  # below secrets for prometheus-yace-exporter
  access_key:  {{ .Values.global.awsCredentials.aws_access_key_id | toString | b64enc | quote }}
  secret_key: {{ .Values.global.awsCredentials.aws_secret_access_key | toString | b64enc | quote }}