{{- define "dockerCreds" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.global.gatewayCreds.environment.DOCKER_SERVER (printf "%s:%s" .Values.global.gatewayCreds.environment.DOCKER_USERNAME .Values.global.gatewayCreds.environment.DOCKER_PASSWORD | b64enc) | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: oc-docker-creds
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson:  {{ template "dockerCreds" . }}