{{- define "base64Secret" }}
{{- printf "Basic %s" (printf "%s:%s" .Values.global.gatewayCreds.environment.KEYCLOAK_CLIENT_ID .Values.global.gatewayCreds.environment.KEYCLOAK_CLIENT_SECRET | b64enc) | b64enc }}
{{- end }}

{{- define "authSecret" }}
{{- $keycloak_url := split "//" .Values.global.gatewayCreds.environment.KEYCLOAK_URL }}
{{- printf "%s/auth/realms/%s" $keycloak_url._1 .Values.global.gatewayCreds.environment.KEYCLOAK_REALM | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: jgateway-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  OAUTH_INTROSPECT_AUTHORIZATION: "{{ template "base64Secret" . }}"
  OAUTH_AUTHORIZATION: "{{ template "base64Secret" . }}"
  OAUTH_INTROSPECT_SERVER: "{{ template "authSecret" . }}"
  OAUTH_LOGIN_SERVER: "{{ template "authSecret" . }}"
  OPSCRUISE_ACCOUNT_ID: "{{ .Values.global.gatewayCreds.environment.OPSCRUISE_ACCOUNT_ID | b64enc }}"
  kafka.bootstrap.servers: "{{ .Values.global.gatewayCreds.environment.OPSCRUISE_ENDPOINT | b64enc }}"
