apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trace-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: trace-router
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    opscruise-chart-version: {{ .Values.global.opscruiseChartVersion }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: trace-router
  template:
    metadata:
      labels:
        app: trace-router
        opscruiseGroup: gateways
        opscruiseProduct: trace-router
        opscruiseStream: opscruise
        {{- if .Values.labels }}
        {{- range $label, $val := .Values.labels }}
        {{ $label }}: {{ $val }}
        {{- end }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/env-config: {{ include (print $.Template.BasePath "/env-config.yaml") . | sha256sum }}
        {{- if .Values.annotations }}
        {{- range $annotation, $val := .Values.annotations }}
        {{ $annotation }}: {{ $val }}
        {{- end }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.trace_router_tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          envFrom:
          {{- toYaml .Values.envFrom | nindent 12 }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}
          
          terminationMessagePath: {{ .Values.terminationMessagePath }}
          terminationMessagePolicy: {{ .Values.terminationMessagePolicy }}

      dnsPolicy: {{ .Values.dnsPolicy }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      
      restartPolicy: {{ .Values.restartPolicy }}
      schedulerName: {{ .Values.schedulerName }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      volumes:
      {{- toYaml .Values.volumes | nindent 8 }}

      {{- if .Values.tolerations }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 6 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
      {{- toYaml .Values.global.tolerations | nindent 6 }}
      {{- end }}

      {{- if .Values.affinity }}
      affinity:
      {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.global.affinity }}
      affinity:
      {{- toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}
      
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      
      {{- if .Values.global.hostAliases }}
      hostAliases:
        {{- toYaml .Values.global.hostAliases | nindent 6 }}
      {{- end }}